### ISSUE TITLE
几个不清楚的问题

### ISSUE THREAD

**Issue by 551552248** [tisan-kit/tisan-web-ide#2]
你好，有几个问题不是很清晰,请教一下：
1、请问 iot board 这个包是放在哪个目录下呢？
2、node app.js 老是出错，请问npm安装依赖包有详细的步骤吗？

**Comment by ruizeng** [comment]
1. iotboard这个包单独的项目在[这里](https://github.com/ruizeng/iot-board)
2. 根目录执行`npm install`就可以自动安装所有依赖
