### ISSUE TITLE
请问开发的nodejs版本是多少

### ISSUE THREAD

**Issue by ailiede** [tisan-kit/tisan-web-ide#6]
执行node app.js时提示
var  conf = jsonconf.parse(f);
                     ^

TypeError: jsonconf.parse is not a function
提示没有jsonconf.parse这个函数
请问这个问题是由于我的nodejs版本不对在造成的吗，我用的是6.1.0版本

**Comment by ailiede** [comment]
出错的代码是在config文件加下面的index.js脚本里面

**Comment by laogewen82** [comment]
我遇到同样的问题，请问你解决了吗

**Comment by ailiede** [comment]
这个问题也不算是解决，自己改写了一个jsonconf.parse版本，但是后续还是有一些语法问题，并且在其他文件里面出现，无法启动，已经搁置好久......请问你也是nodejs的开发者吗？我是刚入门，可以一起讨论讨论，原来的项目开发者似乎已经放弃解答这部分内容

**Comment by laogewen82** [comment]
哦，好的！
jsonconf 这个模块没有了，请问你怎么改写的？

**Comment by ailiede** [comment]
可能表述有点问题，代码不在我手里，时间长了我也记得不太清楚当时具体修改细节，不过大概思路可以和你说一下，原来的代码是：
`var jsonconf = require("jsonconf");
var path = require("path");

var f = path.join(__dirname,"./deploy.json");
var  conf = jsonconf.parse(f);
console.log(conf);
module.exports = conf`
第五行是报错处，主要是调用本目录下的deploy.json文件，而deploy.json文件里面主要是一些配置文件，而错误原因貌似是因为deploy.json文件无法正确读取，所以我直接吧deploy.json文件里面的内容复制出来作为一个初始变量传入module.exports ，这个问题就没有了

**Comment by bugall** [comment]
@ailiede 
您好,这点确实有问题，我晚上会修复下。明天就可以正常使用了。

不好意思,这个问题这么久都没有解决

**Comment by ailiede** [comment]
请问您是原开发者吗？其实这个问题解决以后后续还是会有一些其他地方报错，而且错误信息大多是类似：
TypeError: xxxx is not a function
这些错误看起来都是一些语法错误，但是我找到的资料都是支持这样写的，非常奇怪，能讨论讨论吗？

**Comment by bugall** [comment]
@ailiede 我参与了开发，这个问题明天我修复下。 具体报错还需要有详细的截图

**Comment by ailiede** [comment]
好的，后续如果还有问题我会继续在这里留言

**Comment by laogewen82** [comment]
@bugall  谢谢！ 你来了这些问题可以解决了 ：） 
以后要跟好好学习一下，看你做了很多有意思的东东，呵呵

**Comment by laogewen82** [comment]
请问这个问题修复了吗？ 没有看到刷新啊

**Comment by ailiede** [comment]
@nskyzier 貌似没有，没见更新

**Comment by laogewen82** [comment]
@bugall 最近你有时间吗？ 这个卡壳的问题请帮忙修复一下，期待中。。。。

**Comment by husucceed** [comment]
var conf = jsonconf.pares(f);
TypeEror:jsonconf.parse is not a function 
这个错误怎么解决啊，跟nodejs版本有没有关？

**Comment by Zhang-Jia** [comment]
@bugall问题还没有解决。

**Comment by bugall** [comment]
已经修复了,大家更新下代码就可以了。

**Comment by Zhang-Jia** [comment]
@bugall 下载了最新代码，出现了这个问题
root@iZ94e7vpidfZ:~/tisan-web-ide-master# node app.js
{ msg: '这是部署配置文件',
  host: 'http://localhost',
  listenPort: 8000,
  redis: { host: 'localhost', port: 9000, sessionSecret: 'yoursecret' },
  mysql:
   { connectionLimit: 10,
     host: 'localhost',
     user: 'root',
     password: '220807',
     database: 'PandoCloud',
     port: '3306' },
  qiniu:
   { name: '',
     host: '',
     accountAvatarCallback: '',
     productAvatarCallback: '' },
  mailconfig: [ { host: '', port: 25, auth: [Object] } ],
  mailoptions: { from: '<tisan@pandocloud.com', subject: 'Tisan账号验证', to: '' },
  iframe: 'http://localhost/product/webapp/',
  grpc: [ 'localhost:20311' ],
  docUrl: 'http://localhost/docoment/iframe' }
D0724 00:05:39.028021809   25776 ev_posix.c:101]             Using polling engine: poll
/root/tisan-web-ide-master/service/grpc.js:4
var client = new product_grpc.ProductCMDS(config.grpc[0],grpc.Credentials.createInsecure());
                                                                         ^

TypeError: Cannot read property 'createInsecure' of undefined
    at Object.<anonymous> (/root/tisan-web-ide-master/service/grpc.js:4:74)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/tisan-web-ide-master/routes/workspace.js:3:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

**Comment by ailiede** [comment]
@Zhang-Jia
感觉像是在使用grpc出错，没有安装的原因？
先试试安装grpc
npm install grpc
也可以参考下js的安装使用说明:http://www.grpc.io/docs/tutorials/basic/node.html#defining-the-service
 还有就是config.grpc[0]是不是指向localhost:20311，不太懂js，感觉怪怪的

**Comment by Zhang-Jia** [comment]
@ailiede npm install grpc执行过这句，还是不行，好我看下你后面说的办法。

**Comment by 0uyangsheng** [comment]
一个冲着去赚钱而不是靠兴趣维系的开源项目 ，一旦盈利模式不清晰前途不明朗就 半死不死了。 @Zhang-Jia @ailiede 有没有人成功的完整搭建过整个系统呀。

因为买不到这块开发板，而这个项目又是全部开源，尤其是云平台这块网上开源的很少，我想学习整套架构，所以已经将嵌入式代码这块移植到机智云的开发板中了，接下来准备弄云平台这块，看你们各自纠结各自坑无人回复，有点犹豫。当然 开发者是没有义务回复我们任何问题的。

也不知道是哪个哥们把整套东西改了个名字商业化了，www.acloudiot.com 。
不过我猜 他肯定不赚钱：）

**Comment by coolcm** [comment]
就是你楼上的Zhang-Jia 兄弟成功的完整搭建过整个系统呀。
